version: '3.8'

services:
  dashboard:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=https://api-loglite.duckdns.org
    container_name: loglite-dashboard
    restart: always
    networks:
      - loglite-network

networks:
  loglite-network:
    external: true
